[package]
name = "classify"
version = "0.1.0"
authors = ["WasmEdge"]
edition = "2018"

[lib]
name = "classify"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasmedge_tensorflow_interface = "^0.2.0"
wasm-bindgen = "=0.2.61"
base64 = "0.12.3"
image = { version = "0.23.0", default-features = false, features = ["jpeg", "png", "gif"] }
